### ISSUE TITLE
Different routing sources

### ISSUE THREAD

**Issue by westis** [TrailRouter/public-issues#16]
Are you using GraphHopper and/or OpenRouteService? I understand the latter is free, while the first one is not. Same as with DEM, optionally allow user to enter API key or pay for the service, in case it makes any difference?

**Comment by samcrawford** [comment]
Both Graphhopper and Openrouteservice are free and open source projects, and both also provide paid-for APIs.

Trail Router is built on top of Openrouteservice's open source codebase (which in turn is built on Graphhopper). But I've modified Openrouteservice quite extensively. Neither of them offer anywhere near what Trail Router does. For example, neither provides round-trip routes that consider the features of the land, neither supports the concept of greenery/nature globally (ORS supports it for Germany only), and many more.

So Trail Router is a standalone routing engine, just like Openrouteservice or Graphhopper - you can't just use Trail Router's frontend on top of ORS/GH as they don't support the same features.

**Comment by samcrawford** [comment]
Going to close this as there's nothing for us to do here. Feel free to re-open if I've missed something.
