### ISSUE TITLE
Add an Undo button

### ISSUE THREAD

**Issue by samcrawford** [TrailRouter/public-issues#2]
Mistakes are easily made, an undo button would help significantly.

Open questions:
1) How far back should users be able to undo?
2) Why are users making mistakes in the first place? #https://github.com/TrailRouter/public-issues/issues/1 may be related

**Comment by westis** [comment]
On #2 I often want to undo when I add a waypoint and TR recalculates another part that I did want to include. Sometimes recalculations of a round trip can make the route more complicated if I'm trying to force TR to use a specific way.

Clicking anywhere by mistake (for example not knowing how to create waypoints/drag) could need an undo button. 

How far back? Not too many steps. But maybe a reset button to reset to the original suggested route?

**Comment by westis** [comment]
Another case is on mobile when dragging the map. If I happen to drag on the red line a waypoint is added, which is not what I intend when I swipe to move the map.

**Comment by samcrawford** [comment]
The undo button is now live (bottom right of the screen). It allows you to undo 10 steps back. This limit is arbitrary, it can be changed if need be.

I've not implemented a reset button yet.
