### ISSUE TITLE
Look for larger areas of "greenery"

### ISSUE THREAD

**Issue by westis** [TrailRouter/public-issues#20]
When I look for a new trail I always prefer heading to the forest rather than into town. Possibly, depending on the setting of a user-selectable slider, TR could somehow look around for larger areas of greenery and try to look for a route there first? 

That is, if the user wishes to prefer that. I suppose with the surface slider it will go a long way anyway, particularly if paths are tagged with surface=ground. And if paths have no surface tag (or other tag denoting another kind of path), ayne TR can assume it's a forest path with surface=ground?

Anyway, not to mix things up, this request was about finding larger areas of greenery.

**Comment by samcrawford** [comment]
It does this already when you selected round trip mode or point to point with a target distance (see my original email for details). I'll write this up into a technical blog post soon.

At the moment there's no separate option to enable this. It's switched on automatically when Prefer Green Areas is enabled.

Does this make sense? Or are you asking for something different?

**Comment by westis** [comment]
Sounds great!

**Comment by samcrawford** [comment]
Closing. Already implemented. Will consider splitting the option out in the future though.
