### ISSUE TITLE
Changed behaviour of search box

### ISSUE THREAD

**Issue by westis** [TrailRouter/public-issues#29]
Now you can search for a specific location to set the start location. I would suggest the behaviour is changed so that the start location is not set as soon as you select one of the auto-suggestions.

For example, if I want to move the map to a certain town by entering the name of the town, then I want the map to display that town in order for me to zoom in to a specific location to select the start location. But now it automatically sets the start location to whatever is the middle of that town.

**Comment by samcrawford** [comment]
That was actually the original functionality, but I changed it to the current behaviour a few months ago based upon feedback from multiple other users saying that they expected the location to snap to their search location. It's also consistent with how others behave, so I'm inclined to leave it as is.

**Comment by westis** [comment]
Ok. Komoot for example, does not snap, neither does AllTrails or Plotaroute. What "others" are behaving this way?

It's not a major issue, but it annoyed me a bit when I'm looking at another location than my home.

**Comment by samcrawford** [comment]
True, Komoot and others don't do it. Google Maps does. And it was the subject of quite a few complaints/concerns from users early on (as they were searching for routes in distant locations to try it out). So, on balance, I think I'm going to keep the behaviour as it is for now. Maybe in the future there could be an advanced set of options that allows you to disable this snapping.
