### ISSUE TITLE
Show/hide waypoints in list

### ISSUE THREAD

**Issue by westis** [TrailRouter/public-issues#35]
When plotting a lot of waypoints the list of those waypoints (still called by their nearest postal address, which I don't usually think is working well), the list may be quite long. An option to hide the waypoint list (apart from start and end point) would give more map space.

**Comment by samcrawford** [comment]
Hmmm there's already a limit of 7 waypoints that will be shown in the list before scrollbars appear, and there's already a way for users to hide the list completely (clicking on the 'hamburger icon' or the left-arrow in the green bar at the top). I don't really want to add more icons to the unless I really need to. Happy to adjust the max number of waypoints before scrollbars appear.
