### ISSUE TITLE
Overlay of routes from fastestknowntime.com

### ISSUE THREAD

**Issue by samcrawford** [TrailRouter/public-issues#40]
Fastestknowntime.com has some interesting routes. Contact them to see if they'd be willing to provide the routes as an overlay to show in TR.

**Comment by westis** [comment]
Great idea! I suppose they just overlay a GPX file on top of Google Maps (!?!) currently. But I suppose they must do some kind of processing too, as a GPX from a run may include detours etc. Many of those routes are probably already available as hiking routes in OSM, although for running purposes, an overlay specifically with FKT routes can make it easier to find FKT routes nearby.

**Comment by samcrawford** [comment]
A prototype has been developed. Seeking permission from fastestknowntime.com to proceed further. They're on the fence so far.

**Comment by samcrawford** [comment]
Permission was granted, this is live now.
